name: Fix package-lock

on:
  workflow_dispatch:

jobs:
  fix:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Recreate lockfile
        run: |
          rm -f package-lock.json
          npm install
          npm ci

      - name: Commit lockfile
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add package-lock.json
          git commit -m "chore: regenerate package-lock" || echo "Nothing to commit"
          git push
